FORMAT: 1A
HOST: http://54.84.8.232:25890
//DEV4 - 54.84.8.232:25889
//DEV2 - 54.84.8.232:25890
//SMAUG - 10.10.1.239:8889
//HOST: http://10.10.1.239:8889

# CWEBSAPI

# Group Suspension

## Vehicle Suspend List [/vehicle/suspend_list/]

### List All Suspended Vehicles [GET]
Request (application/json)

+ Response 200 (application/json)

    + Attributes
        - status (string, required)
        - result 
            - message (string, required)
            - vehicles (array[SuspensionData])
            - number_of_vehicles (number, required)

## Vehicle suspend [/vehicle/action/]
### Vehicle suspend [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)
    + Attributes
       
        - action (string, required) 
        - vehicle_id (string, required)
        - authority_i (number, required)
        - msg_for_dispatch (string)
        - msg_for_driver (string)
        
    + Body
    
            {
                "action" : "suspend",
                "vehicle_id" : 8080,
                "authority_id" : 999,
                "msg_for_dispatch" :  "test di",
                "msg_for_driver" :   "test"
            }
        



+ Response 200 (application/json)

    + Attributes
        ResultNoDataOK 
        
    + Body
    
            {
        
                "status": "200 OK",
                "result": {
                "message": "success"
                }
            }
        
## Driver suspend list [/driver/suspend_list/]
### Driver Suspend List [GET]
+ Response 200 (application/json)

    + Body 
    
            {
                "status": "200 OK",
                "result": {
                "number_of_drivers": 1,
                "message": "OK",
                "drivers": [
                    {
                    "suspension_timestamp": 1484771831,
                    "driver_id": 4243,
                    "suspension_time_min": 0,
                    "suspension_time": 1
                    }
                ]
            }        
                
## Driver Suspend [/supervisor/action/]
### Driver Suspend [POST]
+ Request (application/json)

    + Body
    
            {
                "action" : "suspend",
                "driver_id" :  1234,
                "fleet" : 2,
                "authority_id" : "667",
                "msg_id" : 1,
                "db_action_id" : 3572,
                "msg_for_dispatch" : "test message for dispatch test message for dispatch",
                "msg_for_driver" : "test message for driver test message for driver"
            }
    
+ Response 200 (application/json)
    
    + Body 
    
            {
                "status": "200 OK",
                "result": {
                "message": "OK"
                }     
            }

  + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "action": {
                  "type": "string"
                },
                "driver_id": {
                  "type": "integer"
                },
                "fleet": {
                  "type": "integer"
                },
                "authority_id": {
                  "type": "string"
                },
                "msg_id": {
                  "type": "integer"
                },
                "db_action_id": {
                    "type": "string"                
                },
                "msg_for_driver"": {
                  "type": "string"
                },
                "msg_for_dispatch": {
                  "type": "string"
                }
              }
            }


# Group Update-Cancel-No Show

## Cancel Request [/dispatcher/cancel_book_order/]

### Cancel Request [POST]

+ Request (application/json)
    + Attributes
        - fare_number (string, required)
        - fare_type (string)        
        - cancel_reason  (string)
        - cancel_code (number)
     
    

+ Response 200 (application/json)

    + Attributes
        ResultNoDataOK 
        
    + Body
    
            {
        
                "status": "200 OK",
                "result": {
                "message": "success"
                }
            }
        
## Update Fare [/dispatcher/update_fare/]

### Update Fare [POST]

+ Request (application/json)
    + Attributes
        - fare_number (string, required)    
        - action (string, required)
        - operator_id (number)
        - operator_name (string)
        - taxi (number)
        - fleet (number)
        - reason  (string)
        - cancel_code (number)
     
        

+ Response 200 (application/json)

    + Attributes
        ResultNoDataOK 
        
    + Body
    
            {
        
                "status": "200 OK",
                "result": {
                "message": "success"
                }
            }
            
# Data Structures
## CancelFareRequest (object)
    - fare_type: (string)
    - operator_id: number
    - taxi: number
    - fleet: number
    - fare_number: string
    - cancel_reason : string
    - cancel_code: number
    
## UpdateFareRequest (object)
    - action: (string)
    - operator_id: number
    - operator_name: string
    - taxi: number
    - fleet: number
    - fare_number: string
    - reason : string    
    
## SuspendVehicle (object)
    - status: (number)
    - vehicle_id: number
## SuspensionData (object)
    - vehicle_id: (integer)
    - suspension_timestamp: (integer)
    - suspension_time_min: (integer)
    - authority_id: (integer)
    - suspension_time: (integer)
    - suspension_reasons: array[string]
## ResultNoDataOK (object)
    - status (string)
    - result:
        - message (string)